[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Ajustes opcionales
build_flags = -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_ERROR

lib_deps =
  knolleary/PubSubClient
  adafruit/Adafruit GFX Library
  adafruit/Adafruit GC9A01A
  adafruit/Adafruit NeoPixel
  bblanchon/ArduinoJson
  tzapu/WiFiManager

; Si quieres fijar versiones, usa @x.y.z tras el nombre de la librería
